### ISSUE TITLE
Consider using dconf module

### ISSUE THREAD

**Issue by radek-sprta** [PeterMosmans/ansible-role-customize-gnome#13]
Hello,
I think it might be worth considering using the `dconf` module (https://docs.ansible.com/ansible/latest/collections/community/general/dconf_module.html) over command. It seams to work better at least in some cases. The following fails with `customize_gnome`

```yaml
gnome_dconf:
- key: /org/gnome/desktop/wm/preferences/button-layout                                                                                                                       
  value: "'close,minimize,maximize:'"
```
returning

```
error: 0-5:unknown keyword
```

But it works fine, when using `dconf` module.
