### ISSUE TITLE
Gnome Extensions do not appear as installed

### ISSUE THREAD

**Issue by neildeadman** [PeterMosmans/ansible-role-customize-gnome#14]
Hello, I have been using Ansible for barely 2 days now. I've made some great progress, but one of the things I want to do is automatically install Gnome extensions, so I was pleased to find your custom role for this (and more!).

However, nothing I try seems to get it to work...

Here is my playbook:

```
- hosts: all
  become: true
  become_method: sudo
  roles:
    - role: petermosmans.customize-gnome
  vars:
    gnome_extensions:
      - url: https://extensions.gnome.org/download-extension/hidetopbar@mathieu.bidon.ca.shell-extension.zip?version_tag=6450
        name: hidetopbar@mathieu.bidon.ca
      - id: 15
        enable: yes
    gnome_user: nmd
    gtk_version: 3.0
```

Which I took from your example (with other bits stripped out).

I see the playbook complete, and it appears to do the relevant tasks, with the files appearing in `~/.local/share/gnome-shell/extensions/`, but they do not list when I run `gnome-settings list` or if I browse to [https://extensions.gnome.org/local/](url).

I'm sure this is me rather than an issue with your code, but I wasn't sure where else I could ask....
