### ISSUE TITLE
Shell extensions don't get updated

### ISSUE THREAD

**Issue by grdryn** [PeterMosmans/ansible-role-customize-gnome#17]
Hi! If I install an extension, and then a new version becomes available, I can update that from extensions.gnome.org, but I don't seem to be able to get this role to update it (even if I specify the `url` field with the `version_tag` part set to the value for the newer version).

Here's a reproducer:

1. Install an older version of an extension first:
```yaml
gnome_extensions:
  - id: 4679
    name: burn-my-windows@schneegans.github.com
    url: https://extensions.gnome.org/download-extension/burn-my-windows@schneegans.github.com.shell-extension.zip?version_tag=32456
    enable: yes
```
2. Re-login to get it enabled fully (Wayland...)
3. Try to update to the new version:
```yaml
gnome_extensions:
  - id: 4679
    name: burn-my-windows@schneegans.github.com
    url: https://extensions.gnome.org/download-extension/burn-my-windows@schneegans.github.com.shell-extension.zip?version_tag=33113
    enable: yes
```

Is this intentional behaviour, or would being able to update extensions be an improvement? Thanks!
